# Generated by Django 5.0.4 on 2024-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_mate', '0002_alter_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='chore_icon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_img',
            field=models.TextField(blank=True),
        ),
    ]
