# Generated by Django 5.0.4 on 2024-04-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_mate', '0004_alter_message_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='chore_mate.person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chore_mate.person'),
        ),
    ]
