# Generated by Django 5.0.4 on 2024-04-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_mate', '0005_alter_chore_assigned_to_alter_message_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chore_mate.person'),
        ),
    ]
