# Generated by Django 5.0.4 on 2024-04-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_mate', '0008_alter_message_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='chore_mate.person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
