# Generated by Django 5.0.4 on 2024-04-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_mate', '0010_alter_chore_assigned_to_alter_message_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
